version: '3.4'

services:
  angularrecipes:
    image: angular-recipes 
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
